temporary version which does not work as expected
root (INFO): Allocated size: 186, 300
Traceback (most recent call last):
  File "/home/muelli/vcs/geysigning/keysign/scan_barcode.py", line 374, in do_draw
    pattern = cairo.SurfacePattern(pixbuf)
TypeError: must be cairo.Surface, not str
root (DEBUG): Handing of <GstBuffer at 0x7f24b800a5f0>